### ISSUE TITLE
Download limit?

### ISSUE THREAD

**Issue by jonthl** [apologist/eoddata-client#6]
Is there some sort of download limit that eoddata imposes? I've written a script to download intra-day data for three markets @ 10 and 30 minute intervals, using

```python
quote_list_by_date_period_compact(exchange, date, period,  output_format="data-frame")
```
The idea is that I import this data nightly to build up some history. However, sometimes this works beautifully, but other times the request simply times out and I get an empty dataframe. It always takes quite a long time (many 10s of seconds) per request.

**Comment by apologist** [comment]
@jonthl  I have not found any obvious information about limits on their website. If you don't have other options except for this service then I would recommend handling such situations by delaying such downloads since it very likely that a service has some implicit throttling rules.

Regarding a time, the code in this repository can be optimized a little by using tuples instead of class instances and by using generators instead of list comprehensions in some places - if you want you can make some PRs. Also, XML handling I believe can be optimized somehow. But such optimizations won't give a big win since it's just a too long response from their server obviously because of a big amount of data transferring and querying.
